### PR TITLE
Update information about Continous Integration.

### PR DESCRIPTION
**Pull request by PBfordev**
I considered describing in brief what are the  individual CIs used for, but this information is bound to get out of sync with reality sooner or later, so I decided against it and kept it short.

**EDIT**
I have only now noticed the Thanks PR. The CIs are mention there as well, but I do not think that this overlap matters here.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, I agree that this is useful to have and that listing the individual builds here wouldn't be useful, but I wonder if it could be useful to link to their config files?

**Comment by PBfordev** [comment]
>  I wonder if it could be useful to link to their config files?

If you mean the .yml files I considered mentioning those as well but I thought it pointless, as AFAIK, the names and locations for these file are always the same for the given CI so they are easy to find if you want to.

TBH, I am also somewhat hesitant about linking code repository files from the main web. Those links should probably point to the stable branch files; however, those can get pretty outdated with rapid development in the unstable branch.

**Comment by vadz** [comment]
Those are good arguments (especially the second one because in practice people don't seem to know where to find them, providing a counterargument for the first one), so I'll merge this as is, thanks!

**Comment by vadz** [comment]
BTW, does anyone know, by chance, if it's possible to show the status of the last completed build in the badges? Especially AppVeyor is almost always in "running" state, which is not very useful.

**Comment by vadz** [comment]
Sorry, this doesn't work for me somehow because it shows `</div>` tags in the output, this is how it looks for me in FF:

ci

After staring at HTML for a good few minutes, I see nothing wrong with it, but I can't find the way to avoid it other than by removing the two closing tags at the end of the file which are clearly _not_ superfluous. Any idea?

**Comment by PBfordev** [comment]
> Those are good arguments (especially the second one because in practice people don't seem to know where to find them, providing a counterargument for the first one)

If CIs were to be documented, I think it would be best added as a note to `docs\contributing` (and linked from here?).

> Sorry, this doesn't work for me somehow because it shows `</div>` tags in the output, this is how it looks for me in FF:

I have added a "missing" `</p>` tag, hoping this is what somehow confused the HTML generator.

**Comment by vadz** [comment]
I have no idea how did I fail to miss this closing `<p>`, but this was, of course, the problem, thanks for fixing it!

**Pull request closed without merging**
