### PR TITLE
Update coding guidelines

### PR DESCRIPTION
**Pull request by PBfordev**
I have made some changes, taking into account Borland C++ is not supported anymore and wxWidgets now requiring compilers supporting modern C++.

Suggestions for further improvements:
- [ ] Document which C++ standard is allowed.
- [ ] Relax the restrictions on using standard library classes.
- [ ] State whether old-style or scoped enums are to be used in the new code.
- [ ] State whether wxWidgets' or standard smart pointers are to be used in the new code.
- [ ] Update the section in "Indent your code ..." about using automatic formatters (e.g., mention clang-format). TBH, I would just remove all that and kept only the first sentence, I don't think the tool-specific part needs to be here.

I suppose `wxDynamicCast()` is still to be used over `dynamic_cast<>`.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, this should definitely be merged, please let me know if you plan to add more changes to this PR of prefer opening other PRs for them.

**Comment by PBfordev** [comment]
I don't have any more changes planned so this can be merged as is. 

However, I still believe that at least some of the suggestions should be addressed but it is not my place to decide how. Of course, this is not urgent.

**Comment by vadz** [comment]
Yes, this definitely needs another update, I just want to finish many other things first. For now it would be great to at least mark the parts that are out of date as being so...

**Comment by vadz** [comment]
Oh, now that I think about it, we probably should also state that this is valid for 3.3+ but not 3.2.

**Pull request merged**
