### PR TITLE
Blog post on wxNO_IMPLICIT_WXSTRING_ENCODING macro

### PR DESCRIPTION
**Pull request by ardovm**
Following the very long PR on wxWidgets, here is my proposal for a blog post that explain the new macro, why it was introduced and how to use it.

This is my first post on a technical blog and I am trying to make it clear, easy to read and integrated with the other posts.

Please feel absolutely free to criticize _any_ aspect of this post, such as:
- formatting,
- length,
- style, 
- technical errors,
- language errors,
- ...anything else.

### CODE REVIEW

**Comment by vadz** [comment]
This looks great to me, thanks! I might perhaps advise adding something more prescriptive, i.e. a sort of "TL;DR" for the people who'd just like to know how to use it. We could just tell them to try defining `wxNO_IMPLICIT_WXSTRING_ENCODING` and explicitly specify the encoding of the string in all places where the compilation gets broken or something like this.

But I'm more than ready to merge this in the current state too, thanks again!

**Comment by vadz** [comment]
I think should be merged/published, any objections?

**Comment by tierra** [comment]
It might be nice to include a handy reference link to the Unicode overview in the docs for more info as well:
- https://docs.wxwidgets.org/3.1/overview_unicode.html

**Comment by ardovm** [comment]
> It might be nice to include a handy reference link to the Unicode overview in the docs for more info as well:
> 
>     * https://docs.wxwidgets.org/3.1/overview_unicode.html

Thank you for this suggestion.
Due to personal reasons, I would work on this in the week-end, if it's ok for everyone.

**Comment by ardovm** [comment]
I am done.
Looking forward to comments/criticism/suggestions etc.

**Comment by vadz** [comment]
Thanks again! I've merged it and the site has been already updated.

**Pull request merged**
