### PR TITLE
Show download statistics on downloads page

### PR DESCRIPTION
**Pull request by TcT2k**
This shows the download counts and file size in a tooltip. The download statistic is always up to date directly from github via javascript.

image

### CODE REVIEW

**Comment by vadz** [comment]
I agree, a tooltip looks like a better idea. I'm not sure how would this work for the binaries though?

In any case, I'm happy with whatever you do, I'm much less picky with the web stuff than with C++ code :-) TIA!

**Comment by TcT2k** [comment]
@vadz I've moved download count and size to a tooltip. Gives a clean look. It works the same for the binaries downloads.

BTW just as this was recently discussed the windows installer is downloaded even more than the Windows ZIP or 7z (but not more than both combined).

**Comment by tierra** [comment]
I had thought about doing that dynamically in the past, but figured it wouldn't really be very nice to the GitHub API (even if it stays within GitHub's API request limits due to different IPs from visitors hitting it with anonymous API access).

**Comment by TcT2k** [comment]
@tierra I've changed it to use data from `/downloads/downloads.json` which is generated by `_cron/update_download_stats.rb` but that would of course have to be run like the other cron scripts in the folder for it to work correctly. But it's certainly good enough to have the statistics updated daily.

**Comment by tierra** [comment]
The server does have Ruby 2.3 installed, and it can use your script. I can add that into the site update cron once merged.

**Comment by TcT2k** [comment]
@vadz @tierra  Just saw this is still open, could probably be merged some time.

**Comment by vadz** [comment]
Sorry for forgetting about this one, merged now, thanks again!

**Comment by TcT2k** [comment]
@vadz No problem

@tierra 
> The server does have Ruby 2.3 installed, and it can use your script. I can add that into the site update cron once merged.

Could you add this, so the numbers will get updated?

**Comment by tierra** [comment]
@TcT2k / @vadz Sorry it took so long, but I've added this script to the nightly crontab, and running it one-off for now does appear to pull in the tooltips with size and download counts.

**Pull request merged**
