### PR TITLE
Update Building Installers tutorial

### PR DESCRIPTION
**Pull request by PBfordev**
To be entirely honest, I would remove this tutorial altogether.

There still seems to be a lot of outdated information (mostly in OSX and Linux sections) and it appears the document has little if any wxWidgets specific information. I am also not a fan of having personal testimonies in such documents.

### CODE REVIEW

**Comment by vadz** [comment]
I thought to agree that this page should be just removed initially, but then I had a look at the number of visits and it turns out that this is by far the most popular tutorial we have!

Granted, "the most popular" doesn't very popular, since the beginning of the year there were only ~1400 page views, but this compares to 234 for the next one ("writing online help"), 172 for the third one ("accessibility") and just 45 for the "hello world", that I'd expect to be most popular.

So it looks like we could keep it, but it definitely seems weird to talk about Mac OS Classic in 2019, so it would be nice to either remove this section or, at least, a big warning in the beginning saying that parts of this document are out of date.

What do you think?

**Comment by doscott** [comment]
I have to admit this is the first time I have read it.

If it is kept, the last bit of the lead paragraph "My personal favourite at present is Inno Setup combined with ScriptMaker. I can still automate the production of parts of the script (see the files in distrib/msw in the wxWidgets distribution) but use ScriptMaker to edit the parts that would be tedious to edit by hand." should be removed, as it is repeated word for word as the second paragraph of the "Windows Installers" section.

I have never used any of the Apple stuff so I can't comment on their current relevance.

**Comment by PBfordev** [comment]
> 
> If it is kept, the last bit of the lead paragraph...

That duplicate text was the main reason for this PR and it should be fixed in the commit. The Script Maker tool seems no longer exist so I removed that part as well..

**Comment by csomor** [comment]
for macOS only the first paragraph should remain, everything else is outdated. Unfortunately I have not found a decent overview page anymore. The link in that first paragraph is not valid anymore. We could just add a link to

https://developer.apple.com/macos/distribution/

**Comment by PBfordev** [comment]
I have removed all existing OSX instructions and replaced them with basically "go read the official documentation you can find here".

BTW, I have no knowledge whatsoever about OS X, but I have noticed that there is no such OS mentioned in csomor's link above. They only seem to use "macOS" there, e.g., "macOS Mojave" or "macOS Catalina". And "macOS" does not seem to be a broad term for all Apple OSes, as they have macOS, iOS, watchOS, tvOS listed there.

So, that leaves only the badly outdated Linux instructions, but I guess even merging this PR in its current state may be better then keeping the current document.

**Comment by vadz** [comment]
Thanks, this is already quite an improvement, even if it mostly removes things.

"OS X" has been renamed to "macOS" some relatively recent time ago by Apple. We probably should follow their lead and refer to it as such, but I didn't change this just here because I think it should be done globally if we do it.

**Pull request merged**
