### PR TITLE
`wxMaterialDesignArtProvider` post

### PR DESCRIPTION
**Pull request by perazz**
cf. https://groups.google.com/g/wx-dev/c/d7Ed9ooTf5U/m/Yqunz8TjBQAJ

### CODE REVIEW

**Comment by tierra** [comment]
Looks good to me. Was this what you were thinking @vadz ?

**Review by vadz — COMMENTED** [review]
Sorry for the delay, this looks very good but I just wonder if it would be worth to include a (small) screenshot here? If not, let's merge it as is.

**Comment by vadz** [comment]
Excellent, thanks! (Squash) merged now.

P.S. I hadn't tested this locally and didn't realize that the image link didn't work. I've fixed it by hardcoding the actual path, but it seems wrong to put an image from a post into `blog` directory. Not sure how is this supposed to work, to be honest, this seems to be the first ever (!) image in a non-blog post.

**Comment by perazz** [comment]
Sorry about this @vadz, I had followed the instructions but not deployed the whole site on my fork to test it. Thank you for merging!

**Pull request closed without merging**
